remote_theme: byuidesignthinking/just-the-docs

logo: "designthinkinglogo.png"

search_enabled: true
search.heading_level: 3
search.button: true

# ga_tracking: UA-5555555-55
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)